### ISSUE TITLE
To-do for full integration of impropers

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/gmso#341]
List of remaining items to fully integrate impropers as suggested in #338 

- [x] Add improper support to forcefield class
- [x] Add improper support to FF XML reader
- [ ] Add connectivity checks to definitions of angles, dihedrals, and impropers
- [ ] Update naming such that `.n_dihedral = .n_proper = .n_improper`
- [ ] Writer support
